services:
  mysql:
    image: mysql:8.0
    container_name: fitnessjiffy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitnessjiffy
      MYSQL_USER: fitnessjiffy
      MYSQL_PASSWORD: fitnessjiffy
    ports:
      - "3306:3306"
    volumes:
      - fitnessjiffy_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  fitnessjiffy_data:
    driver: local

