# This Github Actions workflow will build and publish a Docker image when the "release" tag is
# added to a commit.
#
# To create or move the "release" tag to the latest commit on main:
#   git checkout main
#   git pull origin main
#   git tag -f release
#   git push origin release --force
#
# Or, to delete and recreate the tag without --force:
#   git tag -d release
#   git push origin :refs/tags/release
#   git tag release
#   git push origin release

name: Docker Release

on:
  push:
    tags:
      - 'release'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD && secrets.DOCKER_REGISTRY }}

    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
          if: ${{ !secrets.DOCKER_USERNAME || !secrets.DOCKER_PASSWORD || !secrets.DOCKER_REGISTRY }}
          run: |
            echo "Required Docker secrets are missing."
            exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t fitnessjiffy:latest .

      - name: Tag Docker image
        run: docker tag fitnessjiffy:latest ${{ secrets.DOCKER_REGISTRY }}/fitnessjiffy:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/fitnessjiffy:latest